const ACTION_TYPES = {
  GET_NEWS_REQUESTED: 'GET_NEWS_REQUESTED',
  GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
  GET_NEWS_REJECTED: 'GET_NEWS_REJECTED',

  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_LOG_OUT: 'AUTH_LOG_OUT',

  AUTH_CHECK_REQUEST: 'AUTH_CHECK_REQUEST',
  AUTH_SIGNIN_REQUEST: 'AUTH_SIGNIN_REQUEST',
  AUTH_SIGNUP_REQUEST: 'AUTH_SIGNUP_REQUEST',

  MODAL_OPEN: 'MODAL_OPEN',
  MODAL_CLOSE: 'MODAL_CLOSE',
};

export default ACTION_TYPES;
